# NOTE: update this with your service name
service: calendar-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ca-central-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: agenda
    #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:ca-central-1:331054046169:table/agenda" # This will be changed soon to our specific resource

functions:
  create:
    handler: handlers/create.main
    events:
      - http:
          path: agendas
          method: post
          authorizer: aws_iam
  get:
    handler: handlers/get.main
    events:
      - http:
          path: agendas/by_id/{id}
          method: get
          authorizer: aws_iam
  list:
    handler: handlers/list.main
    events:
      - http:
          path: agendas/by_date/{date}
          method: get
          authorizer: aws_iam
  fetch:
    handler: handlers/fetch.main
    events:
      - http:
          path: agendas
          method: get
          authorizer: aws_iam
  delete:
    handler: handlers/delete.main
    events:
      - http:
          path: agendas/{id}
          method: delete
          authorizer: aws_iam
  update:
    handler: handlers/update.main
    events:
      - http:
          path: agendas/{id}
          method: put
          authorizer: aws_iam
  # hello:
  #   handler: handlers/handler.hello
  #   events:
  #     - http:
  #         path: hello
  #         method: get
